apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: fastapi-project
  labels:
    app: manager
spec:
  type: NodePort
  selector:
    app: manager-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009