apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: fastapi-project
  labels:
    app: manager
data:
  default.conf: |
    upstream manager_project {
        server manager-service:8000;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://manager_project;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }
    }