pipeline{
    agent any

    stages{
        stage("get Docker version"){
            steps{
                sh "echo $USER"
                sh "docker version"
            }
        }
        stage('Checkout') {
            steps{
                git branch: 'main',
                    url: 'https://github.com/Proxypepe/FastApiDocker.git'
                sh "pwd"
            }
        }

        stage('Build docker image') {
                steps{
                    sh 'docker build -t justhynd/fast_api_expample'
            }
        }

        stage('Push docker image to DockerHub') {
            steps{
                withDockerRegistry(credentialsId: 'docker_hub_justhynd', url: 'https://index.docker.io/v1/') {
                    sh  'docker push justhynd/fast_api_expample:latest'
                }
            }
        }
        stage('Delete docker image locally') {
            steps{
                sh 'docker rmi justhynd/fast_api_expample:latest'
            }
        }
    }
}