---
- name: Deploy ansible playbook
  hosts: kubernetes
  vars:
    apps_location: ~/manager-app-for-cicd/k8s

  tasks:
    - name: Register mk deployment
      command: microk8s kubectl get deployment -n fastapi-project
      register: current

    - name: Delete old section
      command: microk8s kubectl delete -f "{{ apps_location }}/""{{ item }}"
      with_items:
      - code/
      when: current.stdout.find("manager-deployment") != -1

    - name: Pull new version
      command: git pull
      args:
        chdir: ~/manager-app-for-cicd

    - name: Apply new code section
      command: microk8s kubectl apply -f "{{ apps_location }}/""{{ item }}"
      with_items:
      - code/
      - job/
