---
- hosts: kubernetes
  vars:
    apps_location: ~/manager-app-for-cicd/k8s

  tasks:
    - name: delete old section
      command: microk8s kubectl delete -f "{{ apps_location }}/""{{ item }}"
      with_items:
      - code/

    - name: apply new code section
      command: microk8s kubectl delete -f "{{ apps_location }}/""{{ item }}"
      with_items:
      - code/
      - job/
