apiVersion: v1
kind: Service
metadata:
  name: manager-service
  namespace: fastapi-project
  labels:
    app: manager
spec:
  selector:
    app: manager-app
  ports:
    - port: 8000
      targetPort: 8000
